//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ClassificationCompare : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ClassificationCompare(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ClassificationCompare obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ClassificationCompare() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rysyPINVOKE.delete_ClassificationCompare(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ClassificationCompare() : this(rysyPINVOKE.new_ClassificationCompare__SWIG_0(), true) {
  }

  public ClassificationCompare(ClassificationCompare other) : this(rysyPINVOKE.new_ClassificationCompare__SWIG_1(ClassificationCompare.getCPtr(other)), true) {
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
  }

  public ClassificationCompare(uint classes_count, uint top_n_count) : this(rysyPINVOKE.new_ClassificationCompare__SWIG_3(classes_count, top_n_count), true) {
  }

  public ClassificationCompare(uint classes_count) : this(rysyPINVOKE.new_ClassificationCompare__SWIG_4(classes_count), true) {
  }

  public void init(uint classes_count, uint top_n_count) {
    rysyPINVOKE.ClassificationCompare_init__SWIG_0(swigCPtr, classes_count, top_n_count);
  }

  public void init(uint classes_count) {
    rysyPINVOKE.ClassificationCompare_init__SWIG_1(swigCPtr, classes_count);
  }

  public int add(SWIGTYPE_p_std__vectorT_float_t target_output, SWIGTYPE_p_std__vectorT_float_t predicted_output) {
    int ret = rysyPINVOKE.ClassificationCompare_add(swigCPtr, SWIGTYPE_p_std__vectorT_float_t.getCPtr(target_output), SWIGTYPE_p_std__vectorT_float_t.getCPtr(predicted_output));
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void compute() {
    rysyPINVOKE.ClassificationCompare_compute(swigCPtr);
  }

  public bool is_nan_error() {
    bool ret = rysyPINVOKE.ClassificationCompare_is_nan_error(swigCPtr);
    return ret;
  }

  public string asString() {
    string ret = rysyPINVOKE.ClassificationCompare_asString(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_Json__Value asJson() {
    SWIGTYPE_p_Json__Value ret = new SWIGTYPE_p_Json__Value(rysyPINVOKE.ClassificationCompare_asJson(swigCPtr), true);
    return ret;
  }

  public float get_accuracy() {
    float ret = rysyPINVOKE.ClassificationCompare_get_accuracy(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_unsigned_int_t_t get_confusion_matrix() {
    SWIGTYPE_p_std__vectorT_std__vectorT_unsigned_int_t_t ret = new SWIGTYPE_p_std__vectorT_std__vectorT_unsigned_int_t_t(rysyPINVOKE.ClassificationCompare_get_confusion_matrix(swigCPtr), true);
    return ret;
  }

}
