//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class JsonConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal JsonConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(JsonConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~JsonConfig() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rysyPINVOKE.delete_JsonConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_Json__Value result {
    set {
      rysyPINVOKE.JsonConfig_result_set(swigCPtr, SWIGTYPE_p_Json__Value.getCPtr(value));
      if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Json__Value ret = new SWIGTYPE_p_Json__Value(rysyPINVOKE.JsonConfig_result_get(swigCPtr), true);
      if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public JsonConfig() : this(rysyPINVOKE.new_JsonConfig__SWIG_0(), true) {
  }

  public JsonConfig(string json_file_name) : this(rysyPINVOKE.new_JsonConfig__SWIG_1(json_file_name), true) {
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void load(string json_file_name) {
    rysyPINVOKE.JsonConfig_load(swigCPtr, json_file_name);
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void save(string file_name) {
    rysyPINVOKE.JsonConfig_save(swigCPtr, file_name);
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Json__Value get() {
    SWIGTYPE_p_Json__Value ret = new SWIGTYPE_p_Json__Value(rysyPINVOKE.JsonConfig_get(swigCPtr), true);
    return ret;
  }

}
