//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LayerExport : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LayerExport(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LayerExport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LayerExport() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rysyPINVOKE.delete_LayerExport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public LayerExport(string export_path, SWIGTYPE_p_Json__Value json, string layer_prefix, SWIGTYPE_p_sEmbeddedNetShape input_shape, SWIGTYPE_p_sEmbeddedNetShape output_shape) : this(rysyPINVOKE.new_LayerExport(export_path, SWIGTYPE_p_Json__Value.getCPtr(json), layer_prefix, SWIGTYPE_p_sEmbeddedNetShape.getCPtr(input_shape), SWIGTYPE_p_sEmbeddedNetShape.getCPtr(output_shape)), true) {
    if (rysyPINVOKE.SWIGPendingException.Pending) throw rysyPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__string get() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(rysyPINVOKE.LayerExport_get(swigCPtr), false);
    return ret;
  }

  public void save() {
    rysyPINVOKE.LayerExport_save(swigCPtr);
  }

}
