//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rysy {
  public static SWIGTYPE_p_std__vectorT_float_t VectorFloatCreate(uint size) {
    SWIGTYPE_p_std__vectorT_float_t ret = new SWIGTYPE_p_std__vectorT_float_t(rysyPINVOKE.VectorFloatCreate__SWIG_0(size), true);
    return ret;
  }

  public static SWIGTYPE_p_std__vectorT_float_t VectorFloatCreate() {
    SWIGTYPE_p_std__vectorT_float_t ret = new SWIGTYPE_p_std__vectorT_float_t(rysyPINVOKE.VectorFloatCreate__SWIG_1(), true);
    return ret;
  }

}
