//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class rysyPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="SWIGRegisterExceptionCallbacks_rysy")]
    public static extern void SWIGRegisterExceptionCallbacks_rysy(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_rysy")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_rysy(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_rysy(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_rysy(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(rysyPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(rysyPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="SWIGRegisterStringCallback_rysy")]
    public static extern void SWIGRegisterStringCallback_rysy(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_rysy(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static rysyPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageLoad__SWIG_0")]
  public static extern global::System.IntPtr new_ImageLoad__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageLoad__SWIG_1")]
  public static extern global::System.IntPtr new_ImageLoad__SWIG_1(string jarg1, bool jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageLoad__SWIG_2")]
  public static extern global::System.IntPtr new_ImageLoad__SWIG_2(string jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageLoad__SWIG_3")]
  public static extern global::System.IntPtr new_ImageLoad__SWIG_3(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_ImageLoad")]
  public static extern void delete_ImageLoad(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_load__SWIG_0")]
  public static extern void ImageLoad_load__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_load__SWIG_1")]
  public static extern void ImageLoad_load__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_load__SWIG_2")]
  public static extern void ImageLoad_load__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_get")]
  public static extern global::System.IntPtr ImageLoad_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_width")]
  public static extern uint ImageLoad_width(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_height")]
  public static extern uint ImageLoad_height(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_channels")]
  public static extern uint ImageLoad_channels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_grayscale")]
  public static extern bool ImageLoad_grayscale(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_normalise_image__SWIG_0")]
  public static extern void ImageLoad_normalise_image__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_normalise_image__SWIG_1")]
  public static extern void ImageLoad_normalise_image__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageLoad_normalise_image__SWIG_2")]
  public static extern void ImageLoad_normalise_image__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageSave__SWIG_0")]
  public static extern global::System.IntPtr new_ImageSave__SWIG_0(uint jarg1, uint jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ImageSave__SWIG_1")]
  public static extern global::System.IntPtr new_ImageSave__SWIG_1(uint jarg1, uint jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_ImageSave")]
  public static extern void delete_ImageSave(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageSave_save__SWIG_0")]
  public static extern void ImageSave_save__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageSave_save__SWIG_1")]
  public static extern void ImageSave_save__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageSave_save__SWIG_2")]
  public static extern void ImageSave_save__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageSave_show__SWIG_0")]
  public static extern void ImageSave_show__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ImageSave_show__SWIG_1")]
  public static extern void ImageSave_show__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_JsonConfig_result_set")]
  public static extern void JsonConfig_result_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_JsonConfig_result_get")]
  public static extern global::System.IntPtr JsonConfig_result_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_JsonConfig__SWIG_0")]
  public static extern global::System.IntPtr new_JsonConfig__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_JsonConfig__SWIG_1")]
  public static extern global::System.IntPtr new_JsonConfig__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_JsonConfig")]
  public static extern void delete_JsonConfig(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_JsonConfig_load")]
  public static extern void JsonConfig_load(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_JsonConfig_save")]
  public static extern void JsonConfig_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_JsonConfig_get")]
  public static extern global::System.IntPtr JsonConfig_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Log__SWIG_0")]
  public static extern global::System.IntPtr new_Log__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Log__SWIG_1")]
  public static extern global::System.IntPtr new_Log__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_Log")]
  public static extern void delete_Log(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Log_set_output_file_name")]
  public static extern void Log_set_output_file_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Log_put_string")]
  public static extern void Log_put_string(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Timer")]
  public static extern global::System.IntPtr new_Timer();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_Timer")]
  public static extern void delete_Timer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_get_time")]
  public static extern double Timer_get_time(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_get_duration")]
  public static extern double Timer_get_duration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_start")]
  public static extern void Timer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_stop")]
  public static extern void Timer_stop(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_sleep_ms")]
  public static extern void Timer_sleep_ms(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Timer_delay_ms")]
  public static extern void Timer_delay_ms(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Batch__SWIG_0")]
  public static extern global::System.IntPtr new_Batch__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Batch__SWIG_1")]
  public static extern global::System.IntPtr new_Batch__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Batch__SWIG_2")]
  public static extern global::System.IntPtr new_Batch__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_Batch")]
  public static extern void delete_Batch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Batch_create")]
  public static extern void Batch_create(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Batch_get_input_all")]
  public static extern global::System.IntPtr Batch_get_input_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Batch_get_output_all")]
  public static extern global::System.IntPtr Batch_get_output_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DatasetInterface__SWIG_0")]
  public static extern global::System.IntPtr new_DatasetInterface__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DatasetInterface__SWIG_1")]
  public static extern global::System.IntPtr new_DatasetInterface__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DatasetInterface__SWIG_3")]
  public static extern global::System.IntPtr new_DatasetInterface__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_DatasetInterface")]
  public static extern void delete_DatasetInterface(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_input_shape")]
  public static extern global::System.IntPtr DatasetInterface_get_input_shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_output_shape")]
  public static extern global::System.IntPtr DatasetInterface_get_output_shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_training_count")]
  public static extern uint DatasetInterface_get_training_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_testing_count")]
  public static extern uint DatasetInterface_get_testing_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_classes_count")]
  public static extern uint DatasetInterface_get_classes_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_set_training_idx")]
  public static extern void DatasetInterface_set_training_idx(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_set_random_training_idx")]
  public static extern void DatasetInterface_set_random_training_idx(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_training_input")]
  public static extern global::System.IntPtr DatasetInterface_get_training_input(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_training_output")]
  public static extern global::System.IntPtr DatasetInterface_get_training_output(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_training_input_all")]
  public static extern global::System.IntPtr DatasetInterface_get_training_input_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_training_output_all")]
  public static extern global::System.IntPtr DatasetInterface_get_training_output_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_testing_input")]
  public static extern global::System.IntPtr DatasetInterface_get_testing_input(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_testing_output")]
  public static extern global::System.IntPtr DatasetInterface_get_testing_output(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_testing_input_all")]
  public static extern global::System.IntPtr DatasetInterface_get_testing_input_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_get_testing_output_all")]
  public static extern global::System.IntPtr DatasetInterface_get_testing_output_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_set_input_shape")]
  public static extern void DatasetInterface_set_input_shape(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_set_output_shape")]
  public static extern void DatasetInterface_set_output_shape(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_add_training")]
  public static extern void DatasetInterface_add_training(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_add_testing")]
  public static extern void DatasetInterface_add_testing(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_print")]
  public static extern void DatasetInterface_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_clear")]
  public static extern void DatasetInterface_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_normalise_input")]
  public static extern void DatasetInterface_normalise_input(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetInterface_normalise_output")]
  public static extern void DatasetInterface_normalise_output(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DatasetImages")]
  public static extern global::System.IntPtr new_DatasetImages(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_DatasetImages")]
  public static extern void delete_DatasetImages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DatasetMnist")]
  public static extern global::System.IntPtr new_DatasetMnist(string jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_DatasetMnist")]
  public static extern void delete_DatasetMnist(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ClassificationCompare__SWIG_0")]
  public static extern global::System.IntPtr new_ClassificationCompare__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ClassificationCompare__SWIG_1")]
  public static extern global::System.IntPtr new_ClassificationCompare__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ClassificationCompare__SWIG_3")]
  public static extern global::System.IntPtr new_ClassificationCompare__SWIG_3(uint jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ClassificationCompare__SWIG_4")]
  public static extern global::System.IntPtr new_ClassificationCompare__SWIG_4(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_ClassificationCompare")]
  public static extern void delete_ClassificationCompare(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_init__SWIG_0")]
  public static extern void ClassificationCompare_init__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_init__SWIG_1")]
  public static extern void ClassificationCompare_init__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_add")]
  public static extern int ClassificationCompare_add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_compute")]
  public static extern void ClassificationCompare_compute(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_is_nan_error")]
  public static extern bool ClassificationCompare_is_nan_error(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_asString")]
  public static extern string ClassificationCompare_asString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_asJson")]
  public static extern global::System.IntPtr ClassificationCompare_asJson(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_get_accuracy")]
  public static extern float ClassificationCompare_get_accuracy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_get_confusion_matrix")]
  public static extern global::System.IntPtr ClassificationCompare_get_confusion_matrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationCompare_get_class_success_rate")]
  public static extern global::System.IntPtr ClassificationCompare_get_class_success_rate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ClassificationExperiment")]
  public static extern global::System.IntPtr new_ClassificationExperiment(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_ClassificationExperiment")]
  public static extern void delete_ClassificationExperiment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ClassificationExperiment_run")]
  public static extern void ClassificationExperiment_run(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_w_set")]
  public static extern void sShape_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_w_get")]
  public static extern uint sShape_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_h_set")]
  public static extern void sShape_h_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_h_get")]
  public static extern uint sShape_h_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_d_set")]
  public static extern void sShape_d_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_d_get")]
  public static extern uint sShape_d_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_t_set")]
  public static extern void sShape_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_sShape_t_get")]
  public static extern uint sShape_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_sShape")]
  public static extern global::System.IntPtr new_sShape();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_sShape")]
  public static extern void delete_sShape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_0")]
  public static extern global::System.IntPtr new_Shape__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_1")]
  public static extern global::System.IntPtr new_Shape__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_3")]
  public static extern global::System.IntPtr new_Shape__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_4")]
  public static extern global::System.IntPtr new_Shape__SWIG_4(uint jarg1, uint jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_5")]
  public static extern global::System.IntPtr new_Shape__SWIG_5(uint jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_6")]
  public static extern global::System.IntPtr new_Shape__SWIG_6(uint jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Shape__SWIG_7")]
  public static extern global::System.IntPtr new_Shape__SWIG_7(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_Shape")]
  public static extern void delete_Shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_w")]
  public static extern uint Shape_w(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_h")]
  public static extern uint Shape_h(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_d")]
  public static extern uint Shape_d(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_t")]
  public static extern uint Shape_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_get")]
  public static extern global::System.IntPtr Shape_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_set__SWIG_0")]
  public static extern void Shape_set__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_set__SWIG_1")]
  public static extern void Shape_set__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_set__SWIG_2")]
  public static extern void Shape_set__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_set__SWIG_3")]
  public static extern void Shape_set__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_set__SWIG_4")]
  public static extern void Shape_set__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_size")]
  public static extern uint Shape_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Shape_print")]
  public static extern void Shape_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Tensor__SWIG_0")]
  public static extern global::System.IntPtr new_Tensor__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Tensor__SWIG_1")]
  public static extern global::System.IntPtr new_Tensor__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Tensor__SWIG_3")]
  public static extern global::System.IntPtr new_Tensor__SWIG_3(uint jarg1, uint jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Tensor__SWIG_4")]
  public static extern global::System.IntPtr new_Tensor__SWIG_4(uint jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_Tensor__SWIG_5")]
  public static extern global::System.IntPtr new_Tensor__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_Tensor")]
  public static extern void delete_Tensor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_w")]
  public static extern uint Tensor_w(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_h")]
  public static extern uint Tensor_h(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_d")]
  public static extern uint Tensor_d(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_t")]
  public static extern uint Tensor_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_size")]
  public static extern uint Tensor_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_shape")]
  public static extern global::System.IntPtr Tensor_shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_shape_struct")]
  public static extern global::System.IntPtr Tensor_shape_struct(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_init__SWIG_0")]
  public static extern void Tensor_init__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_init__SWIG_1")]
  public static extern void Tensor_init__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_init__SWIG_2")]
  public static extern void Tensor_init__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_from_host__SWIG_0")]
  public static extern void Tensor_set_from_host__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_from_host__SWIG_1")]
  public static extern void Tensor_set_from_host__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_to_host__SWIG_0")]
  public static extern void Tensor_set_to_host__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_to_host__SWIG_1")]
  public static extern void Tensor_set_to_host__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_const")]
  public static extern void Tensor_set_const(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_clear")]
  public static extern void Tensor_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set_random")]
  public static extern void Tensor_set_random(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_set")]
  public static extern void Tensor_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4, uint jarg5, float jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_get")]
  public static extern float Tensor_get(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_print")]
  public static extern void Tensor_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_save")]
  public static extern void Tensor_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_load")]
  public static extern void Tensor_load(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_is_valid")]
  public static extern bool Tensor_is_valid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_add")]
  public static extern void Tensor_add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_sub")]
  public static extern void Tensor_sub(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_mul")]
  public static extern void Tensor_mul(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_concatenate")]
  public static extern void Tensor_concatenate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_split")]
  public static extern void Tensor_split(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_concatenate_time_sequence__SWIG_0")]
  public static extern void Tensor_concatenate_time_sequence__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_concatenate_time_sequence__SWIG_1")]
  public static extern void Tensor_concatenate_time_sequence__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_split_time_sequence")]
  public static extern void Tensor_split_time_sequence(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_norm_l2")]
  public static extern float Tensor_norm_l2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_v_set")]
  public static extern void Tensor_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_Tensor_v_get")]
  public static extern global::System.IntPtr Tensor_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_0")]
  public static extern global::System.IntPtr new_CNN__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_1")]
  public static extern global::System.IntPtr new_CNN__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_3")]
  public static extern global::System.IntPtr new_CNN__SWIG_3(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_4")]
  public static extern global::System.IntPtr new_CNN__SWIG_4(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_5")]
  public static extern global::System.IntPtr new_CNN__SWIG_5(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_6")]
  public static extern global::System.IntPtr new_CNN__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_7")]
  public static extern global::System.IntPtr new_CNN__SWIG_7(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_8")]
  public static extern global::System.IntPtr new_CNN__SWIG_8(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_9")]
  public static extern global::System.IntPtr new_CNN__SWIG_9(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, uint jarg8);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_10")]
  public static extern global::System.IntPtr new_CNN__SWIG_10(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_11")]
  public static extern global::System.IntPtr new_CNN__SWIG_11(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4, float jarg5, float jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_12")]
  public static extern global::System.IntPtr new_CNN__SWIG_12(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_13")]
  public static extern global::System.IntPtr new_CNN__SWIG_13(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_14")]
  public static extern global::System.IntPtr new_CNN__SWIG_14(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNN__SWIG_15")]
  public static extern global::System.IntPtr new_CNN__SWIG_15(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_CNN")]
  public static extern void delete_CNN(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_input_shape")]
  public static extern global::System.IntPtr CNN_get_input_shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_output_shape")]
  public static extern global::System.IntPtr CNN_get_output_shape(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_forward__SWIG_0")]
  public static extern void CNN_forward__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_forward__SWIG_1")]
  public static extern void CNN_forward__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_forward__SWIG_2")]
  public static extern void CNN_forward__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_0")]
  public static extern void CNN_train__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_1")]
  public static extern void CNN_train__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_2")]
  public static extern void CNN_train__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_3")]
  public static extern void CNN_train__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_4")]
  public static extern void CNN_train__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_5")]
  public static extern void CNN_train__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_6")]
  public static extern void CNN_train__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train__SWIG_7")]
  public static extern void CNN_train__SWIG_7(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_train_from_error")]
  public static extern void CNN_train_from_error(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_error_back")]
  public static extern global::System.IntPtr CNN_get_error_back(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_kernel_visualisation__SWIG_0")]
  public static extern global::System.IntPtr CNN_kernel_visualisation__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_kernel_visualisation__SWIG_1")]
  public static extern void CNN_kernel_visualisation__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_activity_visualisation")]
  public static extern void CNN_activity_visualisation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_heatmap_compute")]
  public static extern global::System.IntPtr CNN_heatmap_compute(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_heatmap_visualisation")]
  public static extern void CNN_heatmap_visualisation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_set_training_mode")]
  public static extern void CNN_set_training_mode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_unset_training_mode")]
  public static extern void CNN_unset_training_mode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_is_training_mode")]
  public static extern bool CNN_is_training_mode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_reset")]
  public static extern void CNN_reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_add_layer__SWIG_0")]
  public static extern global::System.IntPtr CNN_add_layer__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_add_layer__SWIG_1")]
  public static extern global::System.IntPtr CNN_add_layer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_add_layer__SWIG_2")]
  public static extern global::System.IntPtr CNN_add_layer__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_asString")]
  public static extern string CNN_asString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_print")]
  public static extern void CNN_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_save")]
  public static extern void CNN_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_load_weights")]
  public static extern void CNN_load_weights(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_layers_count")]
  public static extern uint CNN_get_layers_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_layer_output_size")]
  public static extern uint CNN_get_layer_output_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_layer_output")]
  public static extern global::System.IntPtr CNN_get_layer_output(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_layer_weights_flag")]
  public static extern bool CNN_get_layer_weights_flag(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNN_get_layer_activation_flag")]
  public static extern bool CNN_get_layer_activation_flag(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_CNNVisualisation")]
  public static extern global::System.IntPtr new_CNNVisualisation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_CNNVisualisation")]
  public static extern void delete_CNNVisualisation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNNVisualisation_process")]
  public static extern void CNNVisualisation_process(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_CNNVisualisation_save")]
  public static extern void CNNVisualisation_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ExperienceReplayBuffer__SWIG_0")]
  public static extern global::System.IntPtr new_ExperienceReplayBuffer__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ExperienceReplayBuffer__SWIG_1")]
  public static extern global::System.IntPtr new_ExperienceReplayBuffer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_ExperienceReplayBuffer__SWIG_3")]
  public static extern global::System.IntPtr new_ExperienceReplayBuffer__SWIG_3(uint jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_ExperienceReplayBuffer")]
  public static extern void delete_ExperienceReplayBuffer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_init")]
  public static extern void ExperienceReplayBuffer_init(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_add__SWIG_0")]
  public static extern bool ExperienceReplayBuffer_add__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_add__SWIG_1")]
  public static extern bool ExperienceReplayBuffer_add__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_is_full")]
  public static extern bool ExperienceReplayBuffer_is_full(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_compute__SWIG_0")]
  public static extern void ExperienceReplayBuffer_compute__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_compute__SWIG_1")]
  public static extern void ExperienceReplayBuffer_compute__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_compute__SWIG_2")]
  public static extern void ExperienceReplayBuffer_compute__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_compute__SWIG_3")]
  public static extern void ExperienceReplayBuffer_compute__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_set_curiosity")]
  public static extern void ExperienceReplayBuffer_set_curiosity(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_size")]
  public static extern uint ExperienceReplayBuffer_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_print")]
  public static extern void ExperienceReplayBuffer_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_state")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_state(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_q_values")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_q_values(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_action")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_action(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_reward")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_reward(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_curiosity")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_curiosity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_ExperienceReplayBuffer_get_terminal")]
  public static extern global::System.IntPtr ExperienceReplayBuffer_get_terminal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_0")]
  public static extern global::System.IntPtr new_DQN__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_1")]
  public static extern global::System.IntPtr new_DQN__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, float jarg3, uint jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_2")]
  public static extern global::System.IntPtr new_DQN__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, float jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_3")]
  public static extern global::System.IntPtr new_DQN__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_4")]
  public static extern global::System.IntPtr new_DQN__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQN__SWIG_5")]
  public static extern global::System.IntPtr new_DQN__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_DQN")]
  public static extern void delete_DQN(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_init__SWIG_0")]
  public static extern void DQN_init__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4, uint jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_init__SWIG_1")]
  public static extern void DQN_init__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_init__SWIG_2")]
  public static extern void DQN_init__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_init__SWIG_3")]
  public static extern void DQN_init__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add_layer__SWIG_0")]
  public static extern void DQN_add_layer__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add_layer__SWIG_1")]
  public static extern void DQN_add_layer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_forward__SWIG_0")]
  public static extern global::System.IntPtr DQN_forward__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_forward__SWIG_1")]
  public static extern global::System.IntPtr DQN_forward__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_get_q_values")]
  public static extern global::System.IntPtr DQN_get_q_values(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add__SWIG_0")]
  public static extern bool DQN_add__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add__SWIG_1")]
  public static extern bool DQN_add__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add__SWIG_2")]
  public static extern bool DQN_add__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_add__SWIG_3")]
  public static extern bool DQN_add__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_is_full")]
  public static extern bool DQN_is_full(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_train")]
  public static extern void DQN_train(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_print")]
  public static extern void DQN_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_print_buffer")]
  public static extern void DQN_print_buffer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_save")]
  public static extern void DQN_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_load_weights")]
  public static extern void DQN_load_weights(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_kernel_visualisation")]
  public static extern void DQN_kernel_visualisation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_activity_visualisation")]
  public static extern void DQN_activity_visualisation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQN_heatmap_visualisation")]
  public static extern void DQN_heatmap_visualisation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQNA__SWIG_0")]
  public static extern global::System.IntPtr new_DQNA__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQNA__SWIG_1")]
  public static extern global::System.IntPtr new_DQNA__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, float jarg3, uint jarg4, string jarg5, string jarg6, string jarg7);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_DQNA__SWIG_2")]
  public static extern global::System.IntPtr new_DQNA__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_DQNA")]
  public static extern void delete_DQNA(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_init")]
  public static extern void DQNA_init(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4, uint jarg5, string jarg6, string jarg7, string jarg8);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_forward")]
  public static extern global::System.IntPtr DQNA_forward(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_get_q_values")]
  public static extern global::System.IntPtr DQNA_get_q_values(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_add__SWIG_0")]
  public static extern bool DQNA_add__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_add__SWIG_1")]
  public static extern bool DQNA_add__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_is_full")]
  public static extern bool DQNA_is_full(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_train")]
  public static extern void DQNA_train(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_print")]
  public static extern void DQNA_print(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_print_buffer")]
  public static extern void DQNA_print_buffer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_save")]
  public static extern void DQNA_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DQNA_load_weights")]
  public static extern void DQNA_load_weights(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_LayerExport")]
  public static extern global::System.IntPtr new_LayerExport(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_LayerExport")]
  public static extern void delete_LayerExport(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_LayerExport_get")]
  public static extern global::System.IntPtr LayerExport_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_LayerExport_save")]
  public static extern void LayerExport_save(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_EmbeddedNetworkTest")]
  public static extern global::System.IntPtr new_EmbeddedNetworkTest(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_EmbeddedNetworkTest")]
  public static extern void delete_EmbeddedNetworkTest(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_EmbeddedNetworkTest_process")]
  public static extern float EmbeddedNetworkTest_process(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_new_EmbeddedNetworkExport")]
  public static extern global::System.IntPtr new_EmbeddedNetworkExport(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_delete_EmbeddedNetworkExport")]
  public static extern void delete_EmbeddedNetworkExport(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_EmbeddedNetworkExport_process")]
  public static extern int EmbeddedNetworkExport_process(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_VectorFloatCreate__SWIG_0")]
  public static extern global::System.IntPtr VectorFloatCreate__SWIG_0(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_VectorFloatCreate__SWIG_1")]
  public static extern global::System.IntPtr VectorFloatCreate__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetImages_SWIGUpcast")]
  public static extern global::System.IntPtr DatasetImages_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("rysy", EntryPoint="CSharp_DatasetMnist_SWIGUpcast")]
  public static extern global::System.IntPtr DatasetMnist_SWIGUpcast(global::System.IntPtr jarg1);
}
