//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class sShape : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal sShape(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(sShape obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~sShape() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rysyPINVOKE.delete_sShape(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint w {
    set {
      rysyPINVOKE.sShape_w_set(swigCPtr, value);
    } 
    get {
      uint ret = rysyPINVOKE.sShape_w_get(swigCPtr);
      return ret;
    } 
  }

  public uint h {
    set {
      rysyPINVOKE.sShape_h_set(swigCPtr, value);
    } 
    get {
      uint ret = rysyPINVOKE.sShape_h_get(swigCPtr);
      return ret;
    } 
  }

  public uint d {
    set {
      rysyPINVOKE.sShape_d_set(swigCPtr, value);
    } 
    get {
      uint ret = rysyPINVOKE.sShape_d_get(swigCPtr);
      return ret;
    } 
  }

  public sShape() : this(rysyPINVOKE.new_sShape(), true) {
  }

}
